### ISSUE TITLE
文档勘误

### ISSUE THREAD

**Issue by green961** [eslint/zh-hans.docs.eslint.org#100]
### What problem do you want to solve?

https://zh-hans.eslint.org/docs/latest/use/getting-started

全局安装

也可以全局安装 ESLint 而不仅限于`羡慕`本地

怎么会有 `羡慕` 这个词

https://zh-hans.eslint.org/docs/latest/use/core-concepts

你可以通过设置规则来要求`总是`语句结尾

这里不应该出现 `总是`

### What do you think is the correct solution?

文档勘误

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by green961** [comment]
https://zh-hans.eslint.org/docs/latest/use/core-concepts
通过插件包括自定义规则
通常

**Comment by green961** [comment]
https://zh-hans.eslint.org/docs/latest/use/configure/
或者还可以`用`[命令行](https://zh-hans.eslint.org/docs/latest/use/command-line-interface)上指定配置文件
                   在

处理代码的模式进行`进准`控制
精准

**Comment by kecrily** [comment]
Thanks for finding out and informing us! I'll create a PR to fix the typos.
