### ISSUE TITLE
Incorrect version selected

### ISSUE THREAD

**Issue by nzakas** [eslint/zh-hans.docs.eslint.org#76]
Because this repo is only being updated when we do a release, the docs version dropdown should always be set to the current version. Right now, it's always set to HEAD.

https://deploy-preview-357--zh-hans-eslint.netlify.app/docs/latest/

I believe this is being caused by the logic we have here:
https://github.com/eslint/eslint/blob/main/docs/src/_includes/components/version-switcher.html#L15

The easiest way to fix this would be to rename the `main` branch in this repo to `latest`.

Thoughts?

**Comment by mdjermanovic** [comment]
> The easiest way to fix this would be to rename the `main` branch in this repo to `latest`.

:+1: if we plan to always merge only complete updates (e.g., the entire diff between v8.26.0 and v8.25.0, or between v9.0.0 and the last v8.x.x).

**Comment by kecrily** [comment]
Yes, we plan to merge only the updates between each version. Let us do it!

**Comment by nzakas** [comment]
Done! Making sure Netlify works correctly now.
