### ISSUE TITLE
Missing Chinese links in header

### ISSUE THREAD

**Issue by nzakas** [eslint/zh-hans.docs.eslint.org#79]
https://zh-hans.eslint.org/docs/latest/

The links in the page header are in English while they are in Chinese on https://zh-hans.eslint.org

Docs site:
![Screenshot 2022-11-02 at 11-08-15 文档 - ESLint - Pluggable JavaScript Linter](https://user-images.githubusercontent.com/38546/199567996-4d53bbf3-31b5-462d-acdd-464b5a1e00bc.png)

Main site:
![Screenshot 2022-11-02 at 11-08-55 检测并修复 JavaScript 代码中的问题。 - ESLint - 插件化的 JavaScript 代码检查工具](https://user-images.githubusercontent.com/38546/199568097-24ea68ff-f330-4003-81e6-b68db6dd115b.png)

**Comment by harish-sethuraman** [comment]
closed by #80
